apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: karsa
  labels:
    app: vue
    tier: frontend
spec:
  ports:
  - port: 8000
  selector:
    app: vue
    tier: frontend
  type: NodePort
