version: '3'

services:
  # Creeate database server
  item-db:
    # Use mongo 3 as image of container
    image: mongo:3
    # Restart container when failure to start or run
    restart: on-failure
    # Set network alias to communicate
    networks:
      default:
        aliases:
          - item-db
    # Set persistent volume of mongodb
    volumes:
      - app-db:/data/db
      - app-db:/data/configdb

  # Create application service
  # Using same configuration on .env
  # Untuk menghindari miss konfigurasi
  item-app:
    image: ${GITHUB_REGISTRY}/${GITHUB_USERNAME}/${IMAGE_REPO_NAME}:${IMAGE_TAG}
    # Set network alias to communicate between service/container
    networks:
      default:
        aliases:
          - item-app
    # Expose port to machine
    ports:
      - 80:8080
    # Will restart if container failure to start or run
    restart: on-failure
    # Service tergantung pada service item-db
    depends_on: 
      - item-db

# Define volume to use on this service
volumes:
  app-db: