apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: karsa
  labels:
    app: go-backend-service

spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    tier: backend
  type: ClusterIP