apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: karsa
  labels:
    app: go
    tier: backend

spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: go
    tier: backend
  type: NodePort