apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: karsa
  labels:
    app: go
    tier: backend

spec:
  selector:
    matchLabels:
      app: go
      tier: backend
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: go
        tier: backend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: karsajobs
        image: ghcr.io/geronimo794/karsajobs:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        env:
        - name: APP_PORT
          value: "8080"
        - name: MONGO_HOST
          value: $(MONGO_SERVICE_SERVICE_HOST)
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_PASS
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password

