version: 2.1
orbs:
  docker: circleci/docker@2.2.0

workflows:
  lint-dockerfile:
    jobs:
      - docker/hadolint:
          dockerfiles: Dockerfile
          executor-class: medium
          hadolint-tag: 2.2.0-debian
          ignore-rules: DL4005,DL3008
          trusted-registries: docker.io,ghcr.io
