version: 2.1
orbs:
  docker: circleci/docker@2.2.0

jobs:
  test-app:
    docker:
      - image: cimg/go:1.15.10
    steps:
      - checkout
      - run:
          name: Melakukan testing
          command: go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    docker:
      - image: cimg/go:1.17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          # docker_layer_caching: true
      - run: |
          # Build image from Docker file with var $KARSA_JOB_BE_REPO_NAME and tag $KARSA_JOB_TAG
          # You can see it from .env configuration
          docker build --pull --rm -f "Dockerfile" -t ${KARSA_JOB_BE_REPO_NAME}:${KARSA_JOB_TAG} "."

          # Show all list of docker iamge
          docker image ls

          # Define full new image name, with registry, namespace, repo
          FULL_NEW_IMAGE_NAME=${GITHUB_REGISTRY}/${GITHUB_USERNAME}/${KARSA_JOB_BE_REPO_NAME}:${KARSA_JOB_TAG}

          # Rename previous image repo with new repo and tag
          docker tag ${KARSA_JOB_BE_REPO_NAME}:${KARSA_JOB_TAG} $FULL_NEW_IMAGE_NAME

          # Login with saved Personal Access Token and Github Username
          # You can configure it via .env file
          echo ${GITHUB_PAT} | docker login ghcr.io --username ${GITHUB_USERNAME} --password-stdin

          # Push the image to github registry
          docker push $FULL_NEW_IMAGE_NAME


      # - run:
      #     name: Docker Login
      #     command: echo $GITHUB_PAT | docker login ghcr.io --username $GITHUB_USERNAME --password-stdin
      # - run:
      #     name: Docker Build
      #     command: 'docker build --pull --rm -f "Dockerfile" -t $GITHUB_REGISTRY/$GITHUB_USERNAME/$KARSA_JOB_BE_REPO_NAME:$KARSA_JOB_TAG .'
      # - run:
      #     name: Docker Push
      #     command: 'docker push $GITHUB_REGISTRY/$GITHUB_USERNAME/$KARSA_JOB_BE_REPO_NAME:$KARSA_JOB_TAG .'

      # - docker/build:
      #     image: $GITHUB_REGISTRY/$GITHUB_USERNAME/$KARSA_JOB_BE_REPO_NAME:$KARSA_JOB_TAG
      # - docker/push:
      #     image: $GITHUB_REGISTRY/$GITHUB_USERNAME/$KARSA_JOB_BE_REPO_NAME:$KARSA_JOB_TAG
      # - run:
      #     command: |
      #       echo "Digest is: $(</tmp/digest.txt)"

workflows:
  lint-dockerfile:
    jobs:
      - docker/hadolint:
          dockerfiles: Dockerfile
          executor-class: medium
          hadolint-tag: 2.2.0-debian
          ignore-rules: DL4005,DL3008
          trusted-registries: docker.io,ghcr.io
  test-app:
    jobs:
      - test-app
  build-app-karsajobs:
    jobs:
      - build-app-karsajobs
