version: 2.1
orbs:
  docker: circleci/docker@2.2.0

jobs:
  test-app:
    docker:
      - image: cimg/go:1.15.10
    steps:
      - checkout
      - run:
          name: Melakukan testing
          command: go test -v -short --count=1 $(go list ./...)
  build-app-karsajobs:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - run:
          name: Docker Login
          command: 'echo $GITHUB_PAT | docker login ghcr.io --username $GITHUB_USERNAME --password-stdin'
      - docker/build:
          image: $GITHUB_REGISTRY/$GITHUB_USERNAME/$KARSA_JOB_BE_REPO_NAME:$KARSA_JOB_TAG
      - docker/push:
          image: $GITHUB_REGISTRY/$GITHUB_USERNAME/$KARSA_JOB_BE_REPO_NAME:$KARSA_JOB_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  lint-dockerfile:
    jobs:
      - docker/hadolint:
          dockerfiles: Dockerfile
          executor-class: medium
          hadolint-tag: 2.2.0-debian
          ignore-rules: DL4005,DL3008
          trusted-registries: docker.io,ghcr.io
  test-app:
    jobs:
      - test-app
  build-app-karsajobs:
    jobs:
      - build-app-karsajobs
