# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-local
  namespace: async
spec:
  ports:
  - name: http-stats
    port: 15672
    protocol: TCP
    targetPort: stats
    nodePort: 30100
  selector:
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/name: rabbitmq
  type: NodePort
