apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: karsa
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    nodePort: 31001
  selector:
    app: mongodb
    tier: backend
  type: NodePort
