apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-ss
  namespace: karsa
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: backend
  serviceName: mongodb
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongodb
        tier: backend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:4.0.8
        env:
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
        - name: mongo-pv-data
          mountPath: /data/db
        - name: mongo-config-data
          mountPath: /config
          readOnly: true
        - name: mongo-credentials
          mountPath: /etc/mongo-credentials
          readOnly: true

      volumes:
      - name: mongo-credentials
        secret:
          secretName: mongo-secret
          items:
          - key: MONGO_ROOT_USERNAME
            path: username
          - key: MONGO_ROOT_PASSWORD
            path: password

      - name: mongo-pv-data
        persistentVolumeClaim:
          claimName: mongo-pvc
      - name: mongo-config-data
        configMap:
          name: mongo-cm
          items:
          - key: mongod.conf
            path: mongod.conf

