apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongodb
spec:
  ports:
    - port: 8000
      targetPort: 8081
      protocol: TCP
  selector:
    app: mongodb
    tier: backend
  type: ClusterIP