apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: karsa
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /Users/achrozikin/Documents/k8s.volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: karsa
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
