apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-cm
  namespace: karsa
  labels:
    app: mongodb
data:
  username: mongouser
  mongod.conf: |
    security:
      authorization: enabled
    net:
      bindIp: 0.0.0.0
