apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-stateful-set
  labels:
    app: mongodb
    namespace: karsa
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: backend
  serviceName: mongodb
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongodb
        tier: backend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: mongo:6.0.6
        name: mysql
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
        ports:
        - containerPort: 8081
          name: mongo
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mongo-persistent-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
