apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-stateful-set
  namespace: karsa
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: backend
  serviceName: mongodb
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongodb
        tier: backend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo:6.0.6
        command:
        - mongod
        - --config
        - /etc/mongo/mongod.conf
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts:
        - name: mongo-pv-data
          mountPath: /data/db
        # - name: mongo-pv-configdb
        #   mountPath: /data/configdb

        - name: mongo-config-data
          mountPath: /etc/mongo

      volumes:
      - name: mongo-pv-data
        persistentVolumeClaim:
          claimName: mongo-pvc
      # - name: mongo-pv-configdb
      #   persistentVolumeClaim:
      #     claimName: mongo-pvc

      - name: mongo-config-data
        configMap:
          name: mongo-config-map
          items:
          - key: mongod.conf
            path: mongod.conf

