# Versi dari API untuk konfigurasi
apiVersion: v1
# Jenis dari konfigurasi: Service
kind: Service
# Informasi mengenai konfigurasi
metadata:
  name: order-service
  # Menggunakan namespace async agar lebih mudah untuk debugging
  namespace: async
  # Identifier atau pelabelan saja
  labels:
    app: order
    type: service

# Detail spesifikasi API
spec:
  # Jenis kosong artinya sebagai ClusterIP
  ports:
  # Port yang akan diekspose
  - port: 3000
    # Target port dari aplikasi
    targetPort: 3000
    # Jenis protokol dari aplikasi
    # Digunakan oleh istio
    appProtocol: http

  # Selector digunakan untuk identifier guna menghubungkan deployment
  # Selector yang ada di service, harus sama dengan yang ada di deployment
  selector:
    app: order
    type: service
